export const products = [
  {
    id: 1,
    title: "Creality Ender V2",
    price: 150000,
    stock: 2,
    description: "Impresora FDM",
    category: "impresorasfdm",
    img: "https://res.cloudinary.com/dsqjrzot3/image/upload/v1678554548/impresoraFDM_ooty8h.webp",
    alt: "Imagen de la impresora fdm Creality Ender V2",
  },
  {
    id: 2,
    title: "Creality Ender 3",
    price: 140000,
    stock: 5,
    description: "Impresora FDM",
    category: "impresorasfdm",
    img: "https://res.cloudinary.com/dsqjrzot3/image/upload/v1678554547/crealityender3pro_iuv0xt.webp",
    alt: "Imagen de la impresora fdm Creality Ender 3",
  },
  {
    id: 3,
    title: "Hellbot Apolo Mono",
    price: 190000,
    stock: 2,
    description: "Impresora de Resina DLP",
    category: "impresorasresina",
    img: "https://res.cloudinary.com/dsqjrzot3/image/upload/v1678554547/impresoraResina_lauavp.webp",
    alt: "Imagen de la impresora Resina Hellbot Apolo Mono",
  },
  {
    id: 4,
    title: "Creality Halot One",
    price: 178000,
    stock: 4,
    description: "Impresora de Resina DLP",
    category: "impresorasresina",
    img: "https://res.cloudinary.com/dsqjrzot3/image/upload/v1678554547/ImpresoraHalot_dqaj9x.webp",
    alt: "Imagen de la impresora Resina Creality Halot One",
  },
  {
    id: 5,
    title: "Resina Creality",
    price: 5500,
    stock: 5,
    description: "Resina Dura blanca",
    category: "insumos",
    img: "https://res.cloudinary.com/dsqjrzot3/image/upload/v1678554547/resinaCreality_zuqjnq.webp",
    alt: "Imagen de la Resina Creality",
  },
];
